name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: wk-j/my-web
          tag: latest
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.GITHUB_TOKEN }}
